import { ArrowUpRight, CheckCircle2, Clock3, MoreHorizontal, TrendingUp, Users2, Code2, Trophy } from 'lucide-react'
import { dashboardStats, submissions } from '../data/mock'

const bars=[38,52,44,67,56,73,61,82,70,89,76,94]
const source=[['Two pointers',34],['Hash table',26],['Binary search',18],['Stack',13],['Dynamic programming',9]]
export default function Dashboard({setActive}){
 return <div className="space-y-6">
  <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{dashboardStats.map((s)=><div key={s.label} className="rounded-2xl border border-slate-200 bg-blue-200 p-5 shadow-sm"><div className="flex items-start justify-between"><div><p className="text-sm text-slate-500">{s.label}</p><p className="mt-2 text-3xl font-bold tracking-tight">{s.value}</p></div><div className={`rounded-xl p-2.5 ${s.tone==='indigo'?'bg-indigo-50 text-indigo-600':s.tone==='emerald'?'bg-emerald-50 text-emerald-600':s.tone==='amber'?'bg-amber-50 text-amber-600':'bg-violet-50 text-violet-600'}`}><TrendingUp size={18}/></div></div><div className="mt-4 flex items-center gap-2 text-xs font-medium text-emerald-600"><ArrowUpRight size={14}/>{s.delta}</div></div>)}</section>
  <section className="grid gap-6 xl:grid-cols-[1.5fr_1fr]">
   <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="font-bold">Platform activity</h2><p className="mt-1 text-xs text-slate-400">Submissions over the last 12 weeks</p></div><button className="rounded-lg border border-slate-200 p-2 text-slate-400"><MoreHorizontal size={17}/></button></div><div className="mt-8 h-52"><div className="flex h-full items-end gap-3">{bars.map((v,i)=><div key={i} className="group flex flex-1 flex-col items-center justify-end gap-2"><div className="w-full rounded-t-xl bg-slate-950/90 transition group-hover:bg-indigo-600" style={{height:`${v}%`}}/><span className="text-[10px] text-slate-400">W{i+1}</span></div>)}</div></div></div>
   <div className="rounded-2xl border border-slate-200 bg-blue-100 p-5 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="font-bold">Problem mix</h2><p className="mt-1 text-xs text-slate-400">Most used topic categories</p></div><div className="rounded-xl bg-indigo-50 p-2.5 text-indigo-600"><Code2 size={18}/></div></div><div className="mt-7 space-y-5">{source.map(([name,p])=><div key={name}><div className="mb-2 flex justify-between text-xs"><span className="font-medium text-slate-600">{name}</span><span className="font-semibold text-slate-900">{p}%</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-slate-950" style={{width:`${p*2.2}%`}}/></div></div>)}</div></div>
  </section>
  <section className="grid gap-6 xl:grid-cols-[1.2fr_1fr]">
   <div className="rounded-2xl border border-slate-200 bg-blue-100 shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 p-5"><div><h2 className="font-bold">Recent submissions</h2><p className="mt-1 text-xs text-slate-400">Latest judge activity across the platform</p></div><button onClick={()=>setActive('Submissions')} className="text-xs font-semibold text-indigo-600">View all</button></div><div className="divide-y divide-slate-100">{submissions.map(r=><div key={r[0]} className="grid grid-cols-[1fr_auto] gap-4 p-4 sm:grid-cols-[1.1fr_1fr_auto_auto] sm:items-center"><div><div className="text-sm font-semibold">{r[2]}</div><div className="mt-1 text-xs text-slate-400">{r[1]} · {r[0]}</div></div><div className="hidden text-xs text-slate-500 sm:block">{r[3]}</div><div className={`text-xs font-semibold ${r[4]==='Accepted'?'text-emerald-600':'text-rose-600'}`}>{r[4]}</div><div className="hidden text-xs text-slate-400 md:block">{r[6]}</div></div>)}</div></div>
   <div className="rounded-2xl border border-slate-200 bg-slate-950 p-6 text-white shadow-sm"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-slate-400">Contest center</p><h2 className="mt-2 text-xl font-bold">Weekly Algorithm Sprint</h2><p className="mt-2 text-sm text-slate-400">256 registered participants · Sep 6, 2026</p></div><div className="rounded-2xl bg-white/10 p-3"><Trophy size={22}/></div></div><div className="mt-7 grid grid-cols-3 gap-3">{[['Registered','256'],['Problems','8'],['Duration','90m']].map(([a,b])=><div key={a} className="rounded-2xl border border-white/10 bg-white/5 p-3"><div className="text-[11px] text-slate-400">{a}</div><div className="mt-1 font-bold">{b}</div></div>)}</div><button onClick={()=>setActive('Contests')} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-white px-4 py-3 text-sm font-semibold text-slate-950">Manage contest <ArrowUpRight size={16}/></button></div>
  </section>
 </div>
}
